import Head from "next/head";
import AboutUs from "../components/about-us/aboutUs";
import Banner from "../components/banner/banner";
import Blogs from "../components/blog/blogs";
import Footer from "../components/footer/footer";
import Navigation from "../components/navigation/navigation";
import Services from "../components/service/services";
import WorkHistry from "../components/work-histry/workHistry";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Decbase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Navigation />
        <Banner />
        <Services />
        <AboutUs />
        <WorkHistry />
      </div>
      <Blogs />
      <Footer />
    </div>
  );
}
