import Head from "next/head";
import AboutUs from "../components/about-us/aboutUs";
import Banner from "../components/banner/banner";
import Navigation from "../components/navigation/navigation";
import Services from "../components/service/services";
import WorkHistry from "../components/work-histry/workHistry";
import homeStyle from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Decbase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Banner />
      <Services />
      <AboutUs />
      <WorkHistry />
    </div>
  );
}
